install:
  - "npm install"
  - "npm install bower -g"
  - "bower install"
language: node_js
node_js:
  - "6.3.0"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "gulp test"
notifications:
  email:
    - uxmoon@gmail.com
